# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-stats" do
  name "claude-stats"
  desc "Analytics for Claude Code usage - parse JSONL session files into SQLite"
  homepage "https://github.com/cnu/claude-stats"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-stats"

  on_macos do
    on_intel do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_darwin_amd64.tar.gz"
      sha256 "a4e9329f8c7191418e0d80df2a7b2e0f5c9579e0ff55de8fd37d2e73c49210cb"
    end
    on_arm do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_darwin_arm64.tar.gz"
      sha256 "1d16d95c3596e5a450c467c96321318076226a0b941dad1b4812da633fe5924b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_linux_amd64.tar.gz"
      sha256 "24b854a6cbf6f8c2c4fbf53182a05055889661007a8994893571e4b31e4a787a"
    end
    on_arm do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_linux_arm64.tar.gz"
      sha256 "2705dc8b33e6475a583a7169781499f20b72316b88ed17e3479886cfd62fad02"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-stats"]
    end
  end

  # No zap stanza required
end
