# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-stats" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "14d8691c6000c75530483c53db2fa790bdc4235d9906f930e9f249f4b1b840db"
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f7f55f598499aed5c327bbaa81fc0aaaaa163ef8acb2651b414d0a39b2af05a"
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "76e469b67dabec6f9fea75ee10a64ba201d38e624dcde5f05538ff313ab90c4b"
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3689568e31576215f336bfc21dfc7290fe66a1140503ad549c6857a43bf95dc6"
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_linux_arm64.tar.gz"
    end
  end

  name "claude-stats"
  desc "Analytics for Claude Code usage - parse JSONL session files into SQLite"
  homepage "https://github.com/cnu/claude-stats"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-stats"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-stats"]
    end
  end

  # No zap stanza required

end
