# This file was generated by GoReleaser. DO NOT EDIT.
cask "claude-stats" do
  name "claude-stats"
  desc "Analytics for Claude Code usage - parse JSONL session files into SQLite"
  homepage "https://github.com/cnu/claude-stats"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "claude-stats"

  on_macos do
    on_intel do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_darwin_amd64.tar.gz"
      sha256 "ad31cb495b06130d329b5c5d38ec9f0f7672114768ddfedf2bffac9d9c059e8e"
    end
    on_arm do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_darwin_arm64.tar.gz"
      sha256 "2c3d8cee5bda28d326845bae0502add3bb7033ae2c768c787e76f2b18f47cbe2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_linux_amd64.tar.gz"
      sha256 "4379aee498d1612130ce0fcb2406729493dd6505af8f23d7ebb832450e934a06"
    end
    on_arm do
      url "https://github.com/cnu/claude-stats/releases/download/v#{version}/claude-stats_#{version}_linux_arm64.tar.gz"
      sha256 "74a881fbe763c4359e818f4edc69f7788831d3e2aa8a4cb296bcd2ddf3a6a41b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/claude-stats"]
    end
  end

  # No zap stanza required
end
